# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Christopher Batey 
#email: christopher.batey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Christopher Batey's Website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://batey.info" # the base hostname & protocol for your site
twitter_username: chbatey
github_username:  chbatey
permalink: none
author: Christopher Batey
udemy_jd_course: https://www.udemy.com/course/the-complete-guide-to-running-java-in-docker-and-kubernetes/?referralCode=89474707F75E84F76707

# plugins:
  # - jekyll-seo-tag
  # - jekyll-sitemap

# Build settings
markdown: kramdown

sass:
  sass_dir: css
